//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladoAVG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimuladorAGVEntities : DbContext
    {
        public SimuladorAGVEntities()
            : base("name=SimuladorAGVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ControleTurno> ControleTurno { get; set; }
        public virtual DbSet<NiveisPeso> NiveisPeso { get; set; }
        public virtual DbSet<Paletes> Paletes { get; set; }
        public virtual DbSet<Robos> Robos { get; set; }
        public virtual DbSet<TiposRobo> TiposRobo { get; set; }
    }
}
