//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladoAVG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paletes
    {
        public int IdPalete { get; set; }
        public string CodigoPalete { get; set; }
        public string Carga { get; set; }
        public int IdNivelPeso { get; set; }
        public string Status { get; set; }
        public byte? Linha { get; set; }
        public byte? Coluna { get; set; }
        public System.DateTime RecebidoEm { get; set; }
    
        public virtual NiveisPeso NiveisPeso { get; set; }
    }
}
