//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladoAVG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Robos
    {
        public int IdRobo { get; set; }
        public string Identificador { get; set; }
        public int IdTipoRobo { get; set; }
        public decimal PorcentagemBateria { get; set; }
    
        public virtual TiposRobo TiposRobo { get; set; }
    }
}
