//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimuladoAVG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposRobo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TiposRobo()
        {
            this.Robos = new HashSet<Robos>();
        }
    
        public int IdTipoRobo { get; set; }
        public string NomeTipo { get; set; }
        public decimal ConsumoBateriaPorCiclo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Robos> Robos { get; set; }
    }
}
